### ISSUE TITLE
shopiner

### ISSUE THREAD

**Issue by snnklc** [canavci2016/shopier#1]
M

**Comment by ogulcandegdas** [comment]
okuma/yazmayı öğrenerek entegrasyonu gerçekleştirebilirsiniz

> merhaban modülü siteye nasıl entegre edebilirim

**Comment by reversebro** [comment]
:D @yeninesil çok güzel espri valla sdakdk

**Comment by burakalac4** [comment]
Entegre için video olsa harikulade olur :)

**Comment by canavci2016** [comment]
Arkadaşlar paket haline getirildi. 

aşağıdaki formatta indirip kullanabilirsiniz
composer require canavci2016/shopier
